### ISSUE TITLE
Bot completely broken possibly.

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [SuperWaffleKitty/Project-Luna#7]
![image](https://user-images.githubusercontent.com/54776821/87095466-af1b9900-c238-11ea-98b7-1c4d87831434.png)
Whatever is running on your server doesn't seem to be up-to date. Either it has been partially updated or there is a problem somewhere in the code.

**Comment by SuperWaffleKitty** [comment]
Yeah, I fixed this. I forgot to move the json file which stores guild prefixes to my server which meant that prefixes wouldn't work. It should be working now tho (:
